### PR TITLE
Fix documentation being duplicated with dynamic doc trait

### LINKED ISSUE #2529: IDL Model serializer writes documentation twice
Hi! My team noticed that when you construct a `documentation` trait generically, using `DynamicTrait`, it'll get serialized to the model twice: as `///`, and as a normal `@documentation` trait. There's probably some special-case in the serializer which renders `///` but forgets to remove `@documentation`.

A reproduction in scala-cli, with outputs included:

```scala

//> using dep software.amazon.smithy:smithy-model:1.54.0
//> using option -Wunused:all
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.node.Node
import software.amazon.smithy.model.shapes.ShapeId
import software.amazon.smithy.model.shapes.SmithyIdlModelSerializer
import software.amazon.smithy.model.shapes.StructureShape
import software.amazon.smithy.model.traits.DynamicTrait

import scala.jdk.CollectionConverters.*

import util.chaining.*

val m = Model
  .builder()
  .addShape(
    StructureShape
      .builder()
      .tap {
        _.id(ShapeId.from("demo#Unit"))
      }
      .tap(
        _.addTrait(new DynamicTrait(ShapeId.from("smithy.api#documentation"), Node.from("hello")))
      )
      .build()
  )
  .build()
// m: Model = software.amazon.smithy.model.Model@b3143cd9

val ss =
  SmithyIdlModelSerializer
    .builder
    .build
    .serialize(m)
    .asScala
    .head
    ._2
// ss: String = $version: "2.0"
// 
// namespace demo
// 
/// hello
// @documentation("hello")
// structure Unit {}
```

### PR DESCRIPTION
**Pull request by haydenbaker**
#### Background
* resolve #2529 

#### Links
* Links to additional context, if necessary
* Issue #, if applicable (see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for a list of keywords to use for linking issues)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java [hunk 1]
```diff
@@ -345,4 +348,23 @@ public void coercesInlineIO() {
...
+                                        ShapeId.from("smithy.api#documentation"),
+                                        Node.from("hello")))
+                        .build())
+                .build();
+        Map<Path, String> serialized = SmithyIdlModelSerializer.builder().build().serialize(model);
+        String modelResult = serialized.values().iterator().next().replace("\r\n", "\n");
+
+        // IDL serializer will serialize docs with the special syntax, so we can check that it does not also add
+        // the doc trait itself
+        assertFalse(modelResult.contains("@documentation"));
```
Comment (kstich) [inline smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java:368]: For clarity, maybe worth

```
assertTrue(modelResult.contains("/// hello"));
```

**Review by kstich — APPROVED** [review]
